name: SSH Runner (Cron + Keep Alive)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  push:

jobs:
  run-ssh:
    runs-on: ubuntu-latest

    env:
      TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make ssh.sh executable
        run: chmod +x ./ssh.sh

      - name: Run SSH setup script
        run: ./ssh.sh

      - name: Keep alive
        run: tail -f /dev/null
